//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogdi.Data.DataLoaderGuiApp.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogdi.Data.DataLoaderGuiApp.Ressources.ViewR", typeof(ViewR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your account name.
        /// </summary>
        public static string AccountError {
            get {
                return ResourceManager.GetString("AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be-weekly.
        /// </summary>
        public static string be_weekly {
            get {
                return ResourceManager.GetString("be_weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind To Map.
        /// </summary>
        public static string Bind {
            get {
                return ResourceManager.GetString("Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear All.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Instruments.
        /// </summary>
        public static string CollectionInstruments {
            get {
                return ResourceManager.GetString("CollectionInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Mode.
        /// </summary>
        public static string CollectionMode {
            get {
                return ResourceManager.GetString("CollectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        public static string Column_Name {
            get {
                return ResourceManager.GetString("Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns Metadata.
        /// </summary>
        public static string Columns_Metadata {
            get {
                return ResourceManager.GetString("Columns_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more items cannot be processed since they haven&apos;t been properly configured.
        /// </summary>
        public static string ConfigItemError {
            get {
                return ResourceManager.GetString("ConfigItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily.
        /// </summary>
        public static string daily {
            get {
                return ResourceManager.GetString("daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string Data_Type {
            get {
                return ResourceManager.GetString("Data_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Dictionary/Variables.
        /// </summary>
        public static string DataDictionaryVariables {
            get {
                return ResourceManager.GetString("DataDictionaryVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset.
        /// </summary>
        public static string Dataset {
            get {
                return ResourceManager.GetString("Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset Name (external).
        /// </summary>
        public static string Dataset_Extern {
            get {
                return ResourceManager.GetString("Dataset_Extern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset Name (internal).
        /// </summary>
        public static string Dataset_Intern {
            get {
                return ResourceManager.GetString("Dataset_Intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset Source.
        /// </summary>
        public static string Dataset_Source {
            get {
                return ResourceManager.GetString("Dataset_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete Selection.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured..
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Example: Suppose the dataset contains columns named A and B and you would like push pins text to read as &quot;valueof(A) - valueof(B)&quot;. To achieve that place symbols {0} and {1} into the Push Pin Mapping column against A and B respectively and enter {0} - {1} into the Map Push Pin Format String text field.).
        /// </summary>
        public static string Exemple {
            get {
                return ResourceManager.GetString("Exemple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpiredDate {
            get {
                return ResourceManager.GetString("ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date cannot be less or equal to Release date..
        /// </summary>
        public static string ExpiredDateError {
            get {
                return ResourceManager.GetString("ExpiredDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 years.
        /// </summary>
        public static string five_years {
            get {
                return ResourceManager.GetString("five_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic Coverage.
        /// </summary>
        public static string GeographicCoverage {
            get {
                return ResourceManager.GetString("GeographicCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hourly.
        /// </summary>
        public static string hourly {
            get {
                return ResourceManager.GetString("hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill these columns to get proper columns metadata for the dataset.
        ///
        ///&quot;What it represent?&quot; - choose what best describes the column. If you leave blank you can fill the Description and the Namespace.
        ///
        ///&quot;Description&quot; (only if you left &quot;What it represents?&quot; blank) - enter the description of the column.
        ///
        ///&quot;Namespace&quot; (only if you left &quot;What it represents?&quot; blank) - choose the namespace where your column metadata is defined. Use the format: prefix=&quot;namespace url&quot; (ex: foaf=&quot;http://xmlns.com/foaf/0.1/&quot;). [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your account key.
        /// </summary>
        public static string KeyError {
            get {
                return ResourceManager.GetString("KeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Updated.
        /// </summary>
        public static string LastUpdateDate {
            get {
                return ResourceManager.GetString("LastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude Col. Name.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links/References.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude Col. Name.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Url.
        /// </summary>
        public static string MetadataUrl {
            get {
                return ResourceManager.GetString("MetadataUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly.
        /// </summary>
        public static string monthly {
            get {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        public static string never {
            get {
                return ResourceManager.GetString("never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Planned.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGDI DataLab - Endpoint Settings.
        /// </summary>
        public static string OGDI_Setting {
            get {
                return ResourceManager.GetString("OGDI_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 jear.
        /// </summary>
        public static string one_year {
            get {
                return ResourceManager.GetString("one_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve Original Dataset Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset Partition Key.
        /// </summary>
        public static string PartitionKeyPropertyName {
            get {
                return ResourceManager.GetString("PartitionKeyPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Period Covered.
        /// </summary>
        public static string PeriodCovered {
            get {
                return ResourceManager.GetString("PeriodCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Planned?.
        /// </summary>
        public static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Pin Mapping.
        /// </summary>
        public static string Push_Pin_Mapping {
            get {
                return ResourceManager.GetString("Push_Pin_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarterly.
        /// </summary>
        public static string quarterly {
            get {
                return ResourceManager.GetString("quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Released.
        /// </summary>
        public static string ReleasedDate {
            get {
                return ResourceManager.GetString("ReleasedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What it represent?.
        /// </summary>
        public static string Represent {
            get {
                return ResourceManager.GetString("Represent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset RowKey.
        /// </summary>
        public static string RowKeyPropertyName {
            get {
                return ResourceManager.GetString("RowKeyPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semi anually.
        /// </summary>
        public static string semi_anually {
            get {
                return ResourceManager.GetString("semi_anually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source Timezone.
        /// </summary>
        public static string SourceTimeZoneName {
            get {
                return ResourceManager.GetString("SourceTimeZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Push Pin Text Format String.
        /// </summary>
        public static string StringFormat {
            get {
                return ResourceManager.GetString("StringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet Intern Name is incorrect, it must contain only alpha-numeric characters.
        /// </summary>
        public static string TableError {
            get {
                return ResourceManager.GetString("TableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Set must be at least 3 characters.
        /// </summary>
        public static string TableLengthError {
            get {
                return ResourceManager.GetString("TableLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Documentation.
        /// </summary>
        public static string TechnicalInfo {
            get {
                return ResourceManager.GetString("TechnicalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 years.
        /// </summary>
        public static string ten_years {
            get {
                return ResourceManager.GetString("ten_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with the following fields.
        /// </summary>
        public static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 years.
        /// </summary>
        public static string three_years {
            get {
                return ResourceManager.GetString("three_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 years.
        /// </summary>
        public static string two_years {
            get {
                return ResourceManager.GetString("two_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Frequency.
        /// </summary>
        public static string UpdateFrequency {
            get {
                return ResourceManager.GetString("UpdateFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekly.
        /// </summary>
        public static string weekly {
            get {
                return ResourceManager.GetString("weekly", resourceCulture);
            }
        }
    }
}
