//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogdi.InteractiveSdk.Mvc.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIConstants() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogdi.InteractiveSdk.Mvc.App_GlobalResources.UIConstants", typeof(UIConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 49f06d173d6ae88e.
        /// </summary>
        public static string BMC_AddThisPubKey {
            get {
                return ResourceManager.GetString("BMC_AddThisPubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.addthis.com/bookmark.php?v=20.
        /// </summary>
        public static string BMC_BookmarkPath {
            get {
                return ResourceManager.GetString("BMC_BookmarkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bookmark and Share.
        /// </summary>
        public static string BMC_BookmarkTitle {
            get {
                return ResourceManager.GetString("BMC_BookmarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On click of Bookmark and Share, will open new window for saving this web page as a bookmark.
        /// </summary>
        public static string BMC_ImageAltText {
            get {
                return ResourceManager.GetString("BMC_ImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://s7.addthis.com/static/btn/lg-share-en.gif.
        /// </summary>
        public static string BMC_ImagePath {
            get {
                return ResourceManager.GetString("BMC_ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/Bookmark.txt.
        /// </summary>
        public static string BMC_LongDescPath {
            get {
                return ResourceManager.GetString("BMC_LongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alias.
        /// </summary>
        public static string ContainerComboBoxKeyAttribute {
            get {
                return ResourceManager.GetString("ContainerComboBoxKeyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string ContainerComboBoxValueAttribute {
            get {
                return ResourceManager.GetString("ContainerComboBoxValueAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DataCatalog/DataCatalog.
        /// </summary>
        public static string DataCatalogPagePath {
            get {
                return ResourceManager.GetString("DataCatalogPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get WCF Data Services query syntax.
        /// </summary>
        public static string DBPC_ADOqueryAltText {
            get {
                return ResourceManager.GetString("DBPC_ADOqueryAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/ADOquerysyntax.txt.
        /// </summary>
        public static string DBPC_ADOqueryLongDesc {
            get {
                return ResourceManager.GetString("DBPC_ADOqueryLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WCF Data Services query syntax.
        /// </summary>
        public static string DBPC_ADOqueryTitle {
            get {
                return ResourceManager.GetString("DBPC_ADOqueryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select valid column from list..
        /// </summary>
        public static string DBPC_ChartErrorText {
            get {
                return ResourceManager.GetString("DBPC_ChartErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click for copy to clipboard.
        /// </summary>
        public static string DBPC_CopyDataAltText {
            get {
                return ResourceManager.GetString("DBPC_CopyDataAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/clipboard.jpg.
        /// </summary>
        public static string DBPC_CopyDataImagePath {
            get {
                return ResourceManager.GetString("DBPC_CopyDataImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/Clipboard.txt.
        /// </summary>
        public static string DBPC_CopyDataLongDesc {
            get {
                return ResourceManager.GetString("DBPC_CopyDataLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.daisy.org/.
        /// </summary>
        public static string DBPC_DaisyLink {
            get {
                return ResourceManager.GetString("DBPC_DaisyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Daisy Format.
        /// </summary>
        public static string DBPC_DaisyLinkAltText {
            get {
                return ResourceManager.GetString("DBPC_DaisyLinkAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/DaisyFormat.txt.
        /// </summary>
        public static string DBPC_DaisyLinkLongDesc {
            get {
                return ResourceManager.GetString("DBPC_DaisyLinkLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daisy Link.
        /// </summary>
        public static string DBPC_DaisyLinkTitle {
            get {
                return ResourceManager.GetString("DBPC_DaisyLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interact with the data you selected. Enter filter expression into a text box (text edit area) below and click Run. If you leave the Filter Expression box blank, your query will return all of the data in the selected data set..
        /// </summary>
        public static string DBPC_DataBrowserIntro1 {
            get {
                return ResourceManager.GetString("DBPC_DataBrowserIntro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The results of your query will be shown in tabular format in the Data column. If your query returned KML data, the Map tab will show the geospatial data returned by your query on a [Bing Maps] map. The Code tab provides complete, working sample code for your query for a number of popular development environments..
        /// </summary>
        public static string DBPC_DataBrowserIntro2 {
            get {
                return ResourceManager.GetString("DBPC_DataBrowserIntro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C#/ASP.NET.
        /// </summary>
        public static string DBPC_DefaultBarChartLanguage {
            get {
                return ResourceManager.GetString("DBPC_DefaultBarChartLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (additional $filter parameters...).
        /// </summary>
        public static string DBPC_DefaultFilterText {
            get {
                return ResourceManager.GetString("DBPC_DefaultFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bing Maps.
        /// </summary>
        public static string DBPC_DefaultMapViewLanguage {
            get {
                return ResourceManager.GetString("DBPC_DefaultMapViewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C#/ASP.NET.
        /// </summary>
        public static string DBPC_DefaultPieChartLanguage {
            get {
                return ResourceManager.GetString("DBPC_DefaultPieChartLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à text/plain.
        /// </summary>
        public static string DBPC_DownloadContentType {
            get {
                return ResourceManager.GetString("DBPC_DownloadContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 30.
        /// </summary>
        public static string DBPC_EntityDetailsTableSize {
            get {
                return ResourceManager.GetString("DBPC_EntityDetailsTableSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please check your query syntax and try again..
        /// </summary>
        public static string DBPC_ErrorChkQuery {
            get {
                return ResourceManager.GetString("DBPC_ErrorChkQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This indicates the request to the OGDI service failed.  Check your query for syntax errors and try again..
        /// </summary>
        public static string DBPC_ErrorServiceFail {
            get {
                return ResourceManager.GetString("DBPC_ErrorServiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unexpected error..
        /// </summary>
        public static string DBPC_ErrorUnexpected {
            get {
                return ResourceManager.GetString("DBPC_ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your query returned 0 results..
        /// </summary>
        public static string DBPC_ErrorZeroResults {
            get {
                return ResourceManager.GetString("DBPC_ErrorZeroResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Columns Available.
        /// </summary>
        public static string DBPC_GraphErrorNoColumnAvailable {
            get {
                return ResourceManager.GetString("DBPC_GraphErrorNoColumnAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No graph available.
        /// </summary>
        public static string DBPC_GraphErrorNoGraphAvailable {
            get {
                return ResourceManager.GetString("DBPC_GraphErrorNoGraphAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vertical axis column not available.
        /// </summary>
        public static string DBPC_GraphErrorVerticalAxisMissing {
            get {
                return ResourceManager.GetString("DBPC_GraphErrorVerticalAxisMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No. of occurrences of.
        /// </summary>
        public static string DBPC_GraphOccuranceText {
            get {
                return ResourceManager.GetString("DBPC_GraphOccuranceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --.
        /// </summary>
        public static string DBPC_hashSeparator {
            get {
                return ResourceManager.GetString("DBPC_hashSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Filter Hints.
        /// </summary>
        public static string DBPC_HelpImageAltText {
            get {
                return ResourceManager.GetString("DBPC_HelpImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ~/Descriptions/Filter.txt.
        /// </summary>
        public static string DBPC_HelpImageLongDesc {
            get {
                return ResourceManager.GetString("DBPC_HelpImageLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/help.JPG.
        /// </summary>
        public static string DBPC_HelpImagePath {
            get {
                return ResourceManager.GetString("DBPC_HelpImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/help.JPG.
        /// </summary>
        public static string DBPC_HelpLogoImage {
            get {
                return ResourceManager.GetString("DBPC_HelpLogoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Filter Hints.
        /// </summary>
        public static string DBPC_HelpLogoImageAlternateText {
            get {
                return ResourceManager.GetString("DBPC_HelpLogoImageAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horizontal Axis column.
        /// </summary>
        public static string DBPC_HorizontalAxisColumnText {
            get {
                return ResourceManager.GetString("DBPC_HorizontalAxisColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get ISO 8601.
        /// </summary>
        public static string DBPC_ISO8601AltText {
            get {
                return ResourceManager.GetString("DBPC_ISO8601AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/Iso.txt.
        /// </summary>
        public static string DBPC_ISO8601LongDesc {
            get {
                return ResourceManager.GetString("DBPC_ISO8601LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISO 8601.
        /// </summary>
        public static string DBPC_ISO8601Title {
            get {
                return ResourceManager.GetString("DBPC_ISO8601Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .entityid.
        /// </summary>
        public static string DBPC_KeyAltText {
            get {
                return ResourceManager.GetString("DBPC_KeyAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/key.png.
        /// </summary>
        public static string DBPC_KeyImagePath {
            get {
                return ResourceManager.GetString("DBPC_KeyImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/KeyImg.txt.
        /// </summary>
        public static string DBPC_KeyLongDesc {
            get {
                return ResourceManager.GetString("DBPC_KeyLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App_Data\Xml\Languages.xml.
        /// </summary>
        public static string DBPC_LanguageFilePath {
            get {
                return ResourceManager.GetString("DBPC_LanguageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VEMap control error occured !.
        /// </summary>
        public static string DBPC_mapControlError {
            get {
                return ResourceManager.GetString("DBPC_mapControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NOTE: This is a working sample. You can copy / paste this code into an html file. However, you must download the dependent jquery-1.3.1.min.js file for successful execution. You can download jquery-1.3.1.min.js from.
        /// </summary>
        public static string DBPC_MapViewNote {
            get {
                return ResourceManager.GetString("DBPC_MapViewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://ajax.microsoft.com/ajax/jquery/jquery-1.4.2.min.js.
        /// </summary>
        public static string DBPC_MapViewNoteLink {
            get {
                return ResourceManager.GetString("DBPC_MapViewNoteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à here.
        /// </summary>
        public static string DBPC_MapViewNoteLinkText {
            get {
                return ResourceManager.GetString("DBPC_MapViewNoteLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NOFILTER.
        /// </summary>
        public static string DBPC_NoFilterText {
            get {
                return ResourceManager.GetString("DBPC_NoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to fetch data according to given filter expression.
        /// </summary>
        public static string DBPC_RunAltText {
            get {
                return ResourceManager.GetString("DBPC_RunAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/run.png.
        /// </summary>
        public static string DBPC_RunImagePath {
            get {
                return ResourceManager.GetString("DBPC_RunImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/run.png.
        /// </summary>
        public static string DBPC_RunLogoImage {
            get {
                return ResourceManager.GetString("DBPC_RunLogoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run.
        /// </summary>
        public static string DBPC_RunLogoImageAlternateText {
            get {
                return ResourceManager.GetString("DBPC_RunLogoImageAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run.
        /// </summary>
        public static string DBPC_RunLogoTitle {
            get {
                return ResourceManager.GetString("DBPC_RunLogoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/Run.txt.
        /// </summary>
        public static string DBPC_RunLongDesc {
            get {
                return ResourceManager.GetString("DBPC_RunLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SampleCodeTemplates.
        /// </summary>
        public static string DBPC_SampleCodeFolderName {
            get {
                return ResourceManager.GetString("DBPC_SampleCodeFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Select one).
        /// </summary>
        public static string DBPC_SelectOneText {
            get {
                return ResourceManager.GetString("DBPC_SelectOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Request URI too large to bookmark.
        /// </summary>
        public static string DBPC_TooLongURLForBookmark {
            get {
                return ResourceManager.GetString("DBPC_TooLongURLForBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string DCPC_All {
            get {
                return ResourceManager.GetString("DCPC_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All Available Data Sets.
        /// </summary>
        public static string DCPC_AllDataSetsText {
            get {
                return ResourceManager.GetString("DCPC_AllDataSetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data in the Open Government Data Initiative is organized into containers, each of which represents data from a specific jurisdiction or organization. Within a data set, containers are organized into categories..
        /// </summary>
        public static string DCPC_DataCatalogIntro1 {
            get {
                return ResourceManager.GetString("DCPC_DataCatalogIntro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To discover data sets, first select a container. The grid will show all of the data sets in that container. If you would like to only show data sets in a particular category, click one of the categories along the left side of this page..
        /// </summary>
        public static string DCPC_DataCatalogIntro2 {
            get {
                return ResourceManager.GetString("DCPC_DataCatalogIntro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To query data within a data set, click the name of the data set in the grid. The grid also shows the source of the data set and a brief description. To view extended information about a particular data set (if available), click the &amp;amp;ldquo;More Information&amp;amp;rdquo; link under the data set&apos;s description..
        /// </summary>
        public static string DCPC_DataCatalogIntro3 {
            get {
                return ResourceManager.GetString("DCPC_DataCatalogIntro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Developers/Developers.
        /// </summary>
        public static string DeveloperPagePath {
            get {
                return ResourceManager.GetString("DeveloperPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A video showing how to consume ADO.NET Data Service in a .NET Application.
        /// </summary>
        public static string DPC_AddServiceRefAltText {
            get {
                return ResourceManager.GetString("DPC_AddServiceRefAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://msdn.microsoft.com/en-us/data/cc974504.aspx.
        /// </summary>
        public static string DPC_AddServiceRefLink {
            get {
                return ResourceManager.GetString("DPC_AddServiceRefLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/AddSvcRef.txt.
        /// </summary>
        public static string DPC_AddServiceRefLongDesc {
            get {
                return ResourceManager.GetString("DPC_AddServiceRefLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://msdn.microsoft.com/en-us/library/cc668784(VS.100).aspx.
        /// </summary>
        public static string DPC_ADOLink {
            get {
                return ResourceManager.GetString("DPC_ADOLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get WCF Data Services query syntax.
        /// </summary>
        public static string DPC_ADOLinkAltText {
            get {
                return ResourceManager.GetString("DPC_ADOLinkAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/ADOquerysyntax.txt.
        /// </summary>
        public static string DPC_ADOLinkLongDescPath {
            get {
                return ResourceManager.GetString("DPC_ADOLinkLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WCF Data Services query syntax.
        /// </summary>
        public static string DPC_ADOLinkTitle {
            get {
                return ResourceManager.GetString("DPC_ADOLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get WCF Data Services.
        /// </summary>
        public static string DPC_ADONetAltText {
            get {
                return ResourceManager.GetString("DPC_ADONetAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://msdn.microsoft.com/en-us/data/bb931106.aspx.
        /// </summary>
        public static string DPC_ADONetLink {
            get {
                return ResourceManager.GetString("DPC_ADONetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/ADOServices.txt.
        /// </summary>
        public static string DPC_ADONetLongDescPath {
            get {
                return ResourceManager.GetString("DPC_ADONetLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WCF Data Services.
        /// </summary>
        public static string DPC_ADONetTitle {
            get {
                return ResourceManager.GetString("DPC_ADONetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://bitworking.org/projects/atom/rfc5023.html.
        /// </summary>
        public static string DPC_AtomPublishingLink {
            get {
                return ResourceManager.GetString("DPC_AtomPublishingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Atom Publishing Protocol.
        /// </summary>
        public static string DPC_AtomPublishingLinkAltText {
            get {
                return ResourceManager.GetString("DPC_AtomPublishingLinkAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/AtomPB.tx.
        /// </summary>
        public static string DPC_AtomPublishingLinkLongDescPath {
            get {
                return ResourceManager.GetString("DPC_AtomPublishingLinkLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Atom Publishing Protocol.
        /// </summary>
        public static string DPC_AtomPublishingLinkTitle {
            get {
                return ResourceManager.GetString("DPC_AtomPublishingLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /DataBrowser/dc/CrimeIncidents#param=NOFILTER--DataView--Results.
        /// </summary>
        public static string DPC_DataBrowserPage {
            get {
                return ResourceManager.GetString("DPC_DataBrowserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sample file of service context in ZIP format will be download from Azure data blob storage.
        /// </summary>
        public static string DPC_DownloadAltText {
            get {
                return ResourceManager.GetString("DPC_DownloadAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /images/download.png.
        /// </summary>
        public static string DPC_DownloadImagePath {
            get {
                return ResourceManager.GetString("DPC_DownloadImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://ogdidnld.blob.core.windows.net/samples/OgdiDataServicesContextSample.zip.
        /// </summary>
        public static string DPC_DownloadLink {
            get {
                return ResourceManager.GetString("DPC_DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/Download.txt.
        /// </summary>
        public static string DPC_DownloadLongDescPath {
            get {
                return ResourceManager.GetString("DPC_DownloadLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        public static string DPC_DownloadTitle {
            get {
                return ResourceManager.GetString("DPC_DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://ogdifrance.cloudapp.net:8080/v1/dc/CrimeIncidents?$filter=shift eq &apos;EVN&apos;&amp;amp;format=json.
        /// </summary>
        public static string DPC_EquationLink {
            get {
                return ResourceManager.GetString("DPC_EquationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Google Earth.
        /// </summary>
        public static string DPC_GoogleEarthAltText {
            get {
                return ResourceManager.GetString("DPC_GoogleEarthAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://earth.google.com.
        /// </summary>
        public static string DPC_GoogleEarthLink {
            get {
                return ResourceManager.GetString("DPC_GoogleEarthLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/GoogleEarth.txt.
        /// </summary>
        public static string DPC_GoogleEarthLongDescPath {
            get {
                return ResourceManager.GetString("DPC_GoogleEarthLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Google Earth.
        /// </summary>
        public static string DPC_GoogleEarthTitle {
            get {
                return ResourceManager.GetString("DPC_GoogleEarthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://maps.google.com.
        /// </summary>
        public static string DPC_GoogleMapLink {
            get {
                return ResourceManager.GetString("DPC_GoogleMapLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/GoogleMap.txt.
        /// </summary>
        public static string DPC_GoogleMapLongDescPath {
            get {
                return ResourceManager.GetString("DPC_GoogleMapLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Google Maps.
        /// </summary>
        public static string DPC_GoogleMapsAltText {
            get {
                return ResourceManager.GetString("DPC_GoogleMapsAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Google Maps.
        /// </summary>
        public static string DPC_GoogleMapsTitle {
            get {
                return ResourceManager.GetString("DPC_GoogleMapsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Azure Services Platform home page.
        /// </summary>
        public static string DPC_HomeLinkAltText {
            get {
                return ResourceManager.GetString("DPC_HomeLinkAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/Home.txt.
        /// </summary>
        public static string DPC_HomeLinkLongDescPath {
            get {
                return ResourceManager.GetString("DPC_HomeLinkLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Azure Services Platform.
        /// </summary>
        public static string DPC_HomeLinkTitle {
            get {
                return ResourceManager.GetString("DPC_HomeLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.windowsazure.com/.
        /// </summary>
        public static string DPC_HomePageLink {
            get {
                return ResourceManager.GetString("DPC_HomePageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get IFRAMES-based technique.
        /// </summary>
        public static string DPC_IFrameAltText {
            get {
                return ResourceManager.GetString("DPC_IFrameAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://softwareas.com/cross-domain-communication-with-iframes.
        /// </summary>
        public static string DPC_IFrameLink {
            get {
                return ResourceManager.GetString("DPC_IFrameLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/IFRAMES.txt.
        /// </summary>
        public static string DPC_IFrameLongDescPath {
            get {
                return ResourceManager.GetString("DPC_IFrameLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IFRAMES-based technique.
        /// </summary>
        public static string DPC_IFrameTitle {
            get {
                return ResourceManager.GetString("DPC_IFrameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://en.wikipedia.org/wiki/JSON.
        /// </summary>
        public static string DPC_JSONLink {
            get {
                return ResourceManager.GetString("DPC_JSONLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get JavaScript Object Notation.
        /// </summary>
        public static string DPC_JSONLinkAltText {
            get {
                return ResourceManager.GetString("DPC_JSONLinkAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/Json.txt.
        /// </summary>
        public static string DPC_JSONLinkLongDescPath {
            get {
                return ResourceManager.GetString("DPC_JSONLinkLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JavaScript Object Notation (JSON).
        /// </summary>
        public static string DPC_JSONLinkTitle {
            get {
                return ResourceManager.GetString("DPC_JSONLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get JSONP.
        /// </summary>
        public static string DPC_JSONPAltText {
            get {
                return ResourceManager.GetString("DPC_JSONPAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://en.wikipedia.org/wiki/JSON#JSONP.
        /// </summary>
        public static string DPC_JSONPLink {
            get {
                return ResourceManager.GetString("DPC_JSONPLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/JSONP.txt.
        /// </summary>
        public static string DPC_JSONPLongDescPath {
            get {
                return ResourceManager.GetString("DPC_JSONPLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSONP.
        /// </summary>
        public static string DPC_JSONPTitle {
            get {
                return ResourceManager.GetString("DPC_JSONPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://en.wikipedia.org/wiki/Keyhole_Markup_Language.
        /// </summary>
        public static string DPC_KMLLink {
            get {
                return ResourceManager.GetString("DPC_KMLLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Keyhole Markup Language.
        /// </summary>
        public static string DPC_KMLLinkAltText {
            get {
                return ResourceManager.GetString("DPC_KMLLinkAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/KML.txt.
        /// </summary>
        public static string DPC_KMLLinkLongDescPath {
            get {
                return ResourceManager.GetString("DPC_KMLLinkLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyhole Markup Language (KML).
        /// </summary>
        public static string DPC_KMLLinkTitle {
            get {
                return ResourceManager.GetString("DPC_KMLLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Data Protocol (OData).
        /// </summary>
        public static string DPC_ODataAltText {
            get {
                return ResourceManager.GetString("DPC_ODataAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://odata.org/.
        /// </summary>
        public static string DPC_ODataLink {
            get {
                return ResourceManager.GetString("DPC_ODataLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/AtomPBExt.txt.
        /// </summary>
        public static string DPC_OdataLongDesc {
            get {
                return ResourceManager.GetString("DPC_OdataLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toolkit for PHP with WCF Data Services.
        /// </summary>
        public static string DPC_PHPToolkitAltText {
            get {
                return ResourceManager.GetString("DPC_PHPToolkitAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.interoperabilitybridges.com/projects/toolkit-for-php-with-adonet-data-services-.aspx.
        /// </summary>
        public static string DPC_PHPToolkitLink {
            get {
                return ResourceManager.GetString("DPC_PHPToolkitLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/PHPLib.txt.
        /// </summary>
        public static string DPC_PHPToolkitLongDesc {
            get {
                return ResourceManager.GetString("DPC_PHPToolkitLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Query Timeout and Pagination.
        /// </summary>
        public static string DPC_QueryTimeoutAltText {
            get {
                return ResourceManager.GetString("DPC_QueryTimeoutAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://msdn.microsoft.com/en-us/library/dd135718.aspx.
        /// </summary>
        public static string DPC_QueryTimeoutLink {
            get {
                return ResourceManager.GetString("DPC_QueryTimeoutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/QueryTimeoutPagination.txt.
        /// </summary>
        public static string DPC_QueryTimeoutLongDescPath {
            get {
                return ResourceManager.GetString("DPC_QueryTimeoutLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Query Timeout and Pagination.
        /// </summary>
        public static string DPC_QueryTimeoutTitle {
            get {
                return ResourceManager.GetString("DPC_QueryTimeoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restlet Extension for WCF Data Services.
        /// </summary>
        public static string DPC_RestletExtensionAltText {
            get {
                return ResourceManager.GetString("DPC_RestletExtensionAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.interoperabilitybridges.com/projects/restlet-extension-for-adonet-data-services.aspx.
        /// </summary>
        public static string DPC_RestletExtensionLink {
            get {
                return ResourceManager.GetString("DPC_RestletExtensionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/JavaLib.txt.
        /// </summary>
        public static string DPC_RestletExtensionLongDesc {
            get {
                return ResourceManager.GetString("DPC_RestletExtensionLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://en.wikipedia.org/wiki/Representational_State_Transfer.
        /// </summary>
        public static string DPC_RESTLink {
            get {
                return ResourceManager.GetString("DPC_RESTLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get REST article on the Wikipedia.
        /// </summary>
        public static string DPC_RestLinkAltText {
            get {
                return ResourceManager.GetString("DPC_RestLinkAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/REST.txt.
        /// </summary>
        public static string DPC_RestLinkLongDesc {
            get {
                return ResourceManager.GetString("DPC_RestLinkLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à REST.
        /// </summary>
        public static string DPC_RestLinkTitle {
            get {
                return ResourceManager.GetString("DPC_RestLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Template.
        /// </summary>
        public static string DPC_T4AltText {
            get {
                return ResourceManager.GetString("DPC_T4AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://msdn.microsoft.com/en-us/library/bb126445.aspx.
        /// </summary>
        public static string DPC_T4Link {
            get {
                return ResourceManager.GetString("DPC_T4Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/T4.txt.
        /// </summary>
        public static string DPC_T4LongDescPath {
            get {
                return ResourceManager.GetString("DPC_T4LongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à T4.
        /// </summary>
        public static string DPC_T4Title {
            get {
                return ResourceManager.GetString("DPC_T4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Bing Maps.
        /// </summary>
        public static string DPC_VirtualEarthAltText {
            get {
                return ResourceManager.GetString("DPC_VirtualEarthAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://dev.live.com/virtualearth.
        /// </summary>
        public static string DPC_VirtualEarthLink {
            get {
                return ResourceManager.GetString("DPC_VirtualEarthLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/VE.txt.
        /// </summary>
        public static string DPC_VirtualEarthLongDescPath {
            get {
                return ResourceManager.GetString("DPC_VirtualEarthLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bing Maps.
        /// </summary>
        public static string DPC_VirtualEarthTitle {
            get {
                return ResourceManager.GetString("DPC_VirtualEarthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.microsoft.com/vstudio.
        /// </summary>
        public static string DPC_VStudio {
            get {
                return ResourceManager.GetString("DPC_VStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Microsoft Visual Studio 2008, Service Pack 1.
        /// </summary>
        public static string DPC_VStudioAltText {
            get {
                return ResourceManager.GetString("DPC_VStudioAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/VS2008.txt.
        /// </summary>
        public static string DPC_VStudioLongDescPath {
            get {
                return ResourceManager.GetString("DPC_VStudioLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Microsoft Visual Studio 2008, Service Pack 1.
        /// </summary>
        public static string DPC_VStudioTitle {
            get {
                return ResourceManager.GetString("DPC_VStudioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://maps.yahoo.com.
        /// </summary>
        public static string DPC_YahooMapLink {
            get {
                return ResourceManager.GetString("DPC_YahooMapLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get Yahoo! Maps.
        /// </summary>
        public static string DPC_YahooMapsAltText {
            get {
                return ResourceManager.GetString("DPC_YahooMapsAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/YahooMaps.txt.
        /// </summary>
        public static string DPC_YahooMapsLongDescPath {
            get {
                return ResourceManager.GetString("DPC_YahooMapsLongDescPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yahoo! Maps.
        /// </summary>
        public static string DPC_YahooMapsTitle {
            get {
                return ResourceManager.GetString("DPC_YahooMapsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;The remote server returned an error: (400) Bad Request.&quot; This indicates the request to the OGDI service failed. Check your query for syntax errors and try again..
        /// </summary>
        public static string GC_BadRequestErrorString {
            get {
                return ResourceManager.GetString("GC_BadRequestErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/Collapse.txt.
        /// </summary>
        public static string GC_CollapseImageLongDesc {
            get {
                return ResourceManager.GetString("GC_CollapseImageLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/collapse.jpg.
        /// </summary>
        public static string GC_CollapseImagePath {
            get {
                return ResourceManager.GetString("GC_CollapseImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your request could not be completed or result is empty. Please try again..
        /// </summary>
        public static string GC_ErrorString {
            get {
                return ResourceManager.GetString("GC_ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to show or hide details..
        /// </summary>
        public static string GC_ExpandCollapseImageAltText {
            get {
                return ResourceManager.GetString("GC_ExpandCollapseImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/Expand.txt.
        /// </summary>
        public static string GC_ExpandImageLongDesc {
            get {
                return ResourceManager.GetString("GC_ExpandImageLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/expand.jpg.
        /// </summary>
        public static string GC_ExpandImagePath {
            get {
                return ResourceManager.GetString("GC_ExpandImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to get detailed information.
        /// </summary>
        public static string GC_ExternalLinkAltText {
            get {
                return ResourceManager.GetString("GC_ExternalLinkAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/ExternalLink.png.
        /// </summary>
        public static string GC_ExternalLinkImagePath {
            get {
                return ResourceManager.GetString("GC_ExternalLinkImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/ExternalLink.txt.
        /// </summary>
        public static string GC_ExternalLinkLongDesc {
            get {
                return ResourceManager.GetString("GC_ExternalLinkLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à loading....
        /// </summary>
        public static string GC_LoadingAltText {
            get {
                return ResourceManager.GetString("GC_LoadingAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/loading2.gif.
        /// </summary>
        public static string GC_LoadingImagePath {
            get {
                return ResourceManager.GetString("GC_LoadingImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/Load.txt.
        /// </summary>
        public static string GC_LoadingLongDesc {
            get {
                return ResourceManager.GetString("GC_LoadingLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à As the filter text has been changed, please click on Run button to get fresh data and then navigate.
        /// </summary>
        public static string GC_NoRunClickedError {
            get {
                return ResourceManager.GetString("GC_NoRunClickedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script is disabled on your browser.
        /// </summary>
        public static string GC_NoScriptAltText {
            get {
                return ResourceManager.GetString("GC_NoScriptAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Images/NoscriptInfo.gif.
        /// </summary>
        public static string GC_NoScriptImagePath {
            get {
                return ResourceManager.GetString("GC_NoScriptImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Descriptions/NoScript.txt.
        /// </summary>
        public static string GC_NoScriptLongDesc {
            get {
                return ResourceManager.GetString("GC_NoScriptLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To use complete functionality of this website, script must be enabled on your browser. To get the information about how to enable script, please see your browser help..
        /// </summary>
        public static string GC_NoScriptMessage {
            get {
                return ResourceManager.GetString("GC_NoScriptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 120.
        /// </summary>
        public static string HPC_BlogDescriptionLength {
            get {
                return ResourceManager.GetString("HPC_BlogDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 52.
        /// </summary>
        public static string HPC_BlogTitleLength {
            get {
                return ResourceManager.GetString("HPC_BlogTitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à clsid:d27cdb6e-ae6d-11cf-96b8-444553540000.
        /// </summary>
        public static string HPC_ClassId {
            get {
                return ResourceManager.GetString("HPC_ClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0.
        /// </summary>
        public static string HPC_CodeBase {
            get {
                return ResourceManager.GetString("HPC_CodeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DataCatalog/DataSetList.
        /// </summary>
        public static string HPC_DataCatalogPagePath {
            get {
                return ResourceManager.GetString("HPC_DataCatalogPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Developers.
        /// </summary>
        public static string HPC_DeveloperPagePath {
            get {
                return ResourceManager.GetString("HPC_DeveloperPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à flash_flv_player_4eb5d693-a896-4558-938a-466909aff5c0.
        /// </summary>
        public static string HPC_Id {
            get {
                return ResourceManager.GetString("HPC_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Government Data Initiative.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
    }
}
