//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataConfig.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataConfig.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot connect to your Azure storage account. Please verify your credentials..
        /// </summary>
        public static string CannotConnect {
            get {
                return ResourceManager.GetString("CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot connect to the Azure storage account..
        /// </summary>
        public static string CannotConnectLight {
            get {
                return ResourceManager.GetString("CannotConnectLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your catalog has been added..
        /// </summary>
        public static string CatalogAdded {
            get {
                return ResourceManager.GetString("CatalogAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your catalog has been deleted..
        /// </summary>
        public static string CatalogDeleted {
            get {
                return ResourceManager.GetString("CatalogDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot retrieve this catalog..
        /// </summary>
        public static string CatalogNotFound {
            get {
                return ResourceManager.GetString("CatalogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the selected catalogs and all the associated datasets?.
        /// </summary>
        public static string ConfirmDeleteCatalogs {
            get {
                return ResourceManager.GetString("ConfirmDeleteCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this dataset?.
        /// </summary>
        public static string ConfirmDeleteDataset {
            get {
                return ResourceManager.GetString("ConfirmDeleteDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your dataset has been deleted..
        /// </summary>
        public static string DatasetDeleted {
            get {
                return ResourceManager.GetString("DatasetDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot retrieve this dataset..
        /// </summary>
        public static string DatasetNotFound {
            get {
                return ResourceManager.GetString("DatasetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete the selected catalogs.
        /// </summary>
        public static string DeleteSelectedCatalogs {
            get {
                return ResourceManager.GetString("DeleteSelectedCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your form is incomplete, please fill out missing fields..
        /// </summary>
        public static string IncompleteForm {
            get {
                return ResourceManager.GetString("IncompleteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Storage key is a mandatory field..
        /// </summary>
        public static string MissingStorageKey {
            get {
                return ResourceManager.GetString("MissingStorageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Storage name is a mandatory field..
        /// </summary>
        public static string MissingStorageName {
            get {
                return ResourceManager.GetString("MissingStorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No catalog selected..
        /// </summary>
        public static string NoCatalogSelected {
            get {
                return ResourceManager.GetString("NoCatalogSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First, configure your storage account.
        /// </summary>
        public static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} does not exist..
        /// </summary>
        public static string TableDoesNotExist {
            get {
                return ResourceManager.GetString("TableDoesNotExist", resourceCulture);
            }
        }
    }
}
