//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogdi.InteractiveSdk.Mvc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AzureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogdi.InteractiveSdk.Mvc.AzureResources", typeof(AzureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container cannot be null.
        /// </summary>
        internal static string ContainerCannotBeNull {
            get {
                return ResourceManager.GetString("ContainerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container and tableName should be non-numeric.
        /// </summary>
        internal static string ContainerTableNameNonNumeric {
            get {
                return ResourceManager.GetString("ContainerTableNameNonNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-ms-continuation-NextPartitionKey.
        /// </summary>
        internal static string continuation_nextPartionKey {
            get {
                return ResourceManager.GetString("continuation_nextPartionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-ms-continuation-NextRowKey.
        /// </summary>
        internal static string continuation_nextRowKey {
            get {
                return ResourceManager.GetString("continuation_nextRowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityMetadata.
        /// </summary>
        internal static string metaDataTableName {
            get {
                return ResourceManager.GetString("metaDataTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2005/Atom.
        /// </summary>
        internal static string nsAtom {
            get {
                return ResourceManager.GetString("nsAtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/ado/2007/08/dataservices.
        /// </summary>
        internal static string nsDataServices {
            get {
                return ResourceManager.GetString("nsDataServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/ado/2007/08/dataservices/metadata.
        /// </summary>
        internal static string nsMetadata {
            get {
                return ResourceManager.GetString("nsMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size should not be zero or negative.
        /// </summary>
        internal static string PagesizeNotZEROOrNegative {
            get {
                return ResourceManager.GetString("PagesizeNotZEROOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableName cannot be null.
        /// </summary>
        internal static string TableNameCannotBeNull {
            get {
                return ResourceManager.GetString("TableNameCannotBeNull", resourceCulture);
            }
        }
    }
}
