//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCatalogResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogdi.InteractiveSdk.Mvc.Resources.Views.DataCatalog.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data Catalog.
        /// </summary>
        public static string DataCatalog {
            get {
                return ResourceManager.GetString("DataCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data in the Open Government Data Initiative is organized
        ///into containers, each of which represents data from a specific jurisdiction or organization.
        ///Within a data set, containers are organized into categories..
        /// </summary>
        public static string DataInTheOpenGovernmentDataInitiativeIsOrganized {
            get {
                return ResourceManager.GetString("DataInTheOpenGovernmentDataInitiativeIsOrganized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LEGAL DISCLAIMER.
        /// </summary>
        public static string LegalDisclaimer {
            get {
                return ResourceManager.GetString("LegalDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To discover data sets, first select a container. The grid will show all of the data
        ///sets in that container. If you would like to only show data sets in a particular
        ///category, click one of the categories along the left side of this page..
        /// </summary>
        public static string ToDiscoverDataSets {
            get {
                return ResourceManager.GetString("ToDiscoverDataSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To query data within a data set, click the name of the data set in the grid. The
        ///grid also shows the source of the data set and a brief description. To view extended
        ///information about a particular data set (if available), click the &amp;amp;ldquo;More
        ///Information&amp;amp;rdquo; link under the data set&apos;s description..
        /// </summary>
        public static string ToQueryDataWithinADataSet {
            get {
                return ResourceManager.GetString("ToQueryDataWithinADataSet", resourceCulture);
            }
        }
    }
}
