//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopersResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogdi.InteractiveSdk.Mvc.Resources.Views.Developers.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Libraries.
        /// </summary>
        public static string ClientLibraries {
            get {
                return ResourceManager.GetString("ClientLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers using &lt;a href=&quot;http://microsoft.com/vstudio/&quot; target=&quot;_blank&quot;&gt;Microsoft Visual Studio 2010&lt;/a&gt; (and above) can use &lt;a href=&quot;http://msdn.microsoft.com/en-us/data/bb931106.aspx&quot; target=&quot;_blank&quot;&gt;WCF Data Services&lt;/a&gt; to access data from OGDI DataLab through easy-to-use .NET classes. Within Visual Studio, this is accomplished by using the &lt;a href=&quot;http://msdn.microsoft.com/en-us/library/bb628652.aspx&quot; target=&quot;_blank&quot;&gt;Add Service Reference&lt;/a&gt; feature (see .NET samples on the OGDI DataLab’s Data Brows [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClientLibrariesText {
            get {
                return ResourceManager.GetString("ClientLibrariesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Formats.
        /// </summary>
        public static string DataFormat {
            get {
                return ResourceManager.GetString("DataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;AtomPub&lt;/h4&gt; 
        ///&lt;p&gt;By default, OGDI DataLab returns data in the &lt;a href=&quot;http://www.odata.org/&quot; target=&quot;_blank&quot;&gt;Open Data Protocol (OData)&lt;/a&gt; format. This format extends the broadly adopted &lt;a href=&quot;http://bitworking.org/projects/atom/rfc5023.html&quot; target=&quot;_blank&quot;&gt;Atom Publishing Protocol&lt;/a&gt; and can be easily consumed by a variety of platforms, including Microsoft .NET, Java, Ruby, PHP, and Python. Refer to the code samples on the &lt;a href=&quot;http://ogdifrancex.cloudapp.net/DataBrowser/dc/CrimeIncidents#p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DataFormatText {
            get {
                return ResourceManager.GetString("DataFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string OverView {
            get {
                return ResourceManager.GetString("OverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;strong&gt;OGDI (Open Government Data Initiative) DataLab&lt;/strong&gt; platform leverages by defaut the &lt;a href=&quot;http://azure.microsoft.com/&quot; target=&quot;_blank&quot;&gt;Microsoft Azure Platform&lt;/a&gt;, an open cloud-based runtime and hosting environment helping developers to quickly and easily create, deploy, manage and run applications and Web services across the Internet. The Azure platform allows developers to focus on their core business: applications and Web services. Developers uses their own existing skills (NET, Rub [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OverViewText {
            get {
                return ResourceManager.GetString("OverViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying OGDI DataLab.
        /// </summary>
        public static string QueryingOGDI {
            get {
                return ResourceManager.GetString("QueryingOGDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGDI DataLab exposes data through &lt;a href=&quot;http://en.wikipedia.org/wiki/Representational_state_transfer&quot; target=&quot;_blank&quot;&gt;REST&lt;/a&gt; web services. The basic format of an OGDI DataLab service call is &lt;br/&gt;http://&lt;strong&gt;project&lt;/strong&gt;.cloudapp.net[:8080]/v1/&lt;strong&gt;catalog&lt;/strong&gt;/&lt;strong&gt;dataset&lt;/strong&gt;?&lt;strong&gt;query&lt;/strong&gt;, where: 
        ///&lt;ul&gt;&lt;li&gt;&lt;strong&gt;project&lt;/strong&gt; is the name of the deployment project for the OGDI DataLab platform in Azure (for example, &quot;ogdifrance&quot; for the testing instance provided by [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QueryingOGDIText {
            get {
                return ResourceManager.GetString("QueryingOGDIText", resourceCulture);
            }
        }
    }
}
