//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopersResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogdi.InteractiveSdk.Mvc.Resources.Views.Developers.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Also note that if a property has a null value for a particular entity in the data
        ///			set, it will be omitted entirely from the result set returned by OGDI DataLab. For example,
        ///			in the Crime Incidents data set, the &quot;method&quot; property is only returned for records
        ///			that have a &quot;method&quot; value in the underlying data set. Your application design should
        ///			take this into account and handle potentially missing properties..
        /// </summary>
        public static string AlsoNoteThatIfAPropertyHasANullValue {
            get {
                return ResourceManager.GetString("AlsoNoteThatIfAPropertyHasANullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AtomPub.
        /// </summary>
        public static string AtomPub {
            get {
                return ResourceManager.GetString("AtomPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By default, OGDI DataLab returns data in the &lt;a href=&quot;http://odata.org/&quot;
        ///				target=&quot;_blank&quot;&gt;Open Data Protocol (OData)&lt;/a&gt;&lt;img
        ///					src=&quot;/Images/ExternalLink.png&quot; 
        ///					alt=&quot;Open Data Protocol (OData)&quot;
        ///					longdesc=&quot;/Descriptions/AtomPBExt.txt&quot; /&gt;
        ///			format. This format extends the broadly adopted &lt;a href=&quot;http://bitworking.org/projects/atom/rfc5023.html&quot;
        ///				target=&quot;_blank&quot;&gt;Atom Publishing Protocol&lt;/a&gt;&lt;img
        ///				src=&quot;/Images/ExternalLink.png&quot;
        ///					alt=&quot;Click to get Atom Publishing Protocol&quot;
        ///					title=&quot;Ato [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string ByDefaultOGDIReturnsDataInTheAtomPub {
            get {
                return ResourceManager.GetString("ByDefaultOGDIReturnsDataInTheAtomPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client Libraries.
        /// </summary>
        public static string ClientLibraries {
            get {
                return ResourceManager.GetString("ClientLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;i&gt;container&lt;/i&gt; is the name of the container (for example, &quot;dc&quot; for the District
        ///				of Columbia&apos;s data sets)..
        /// </summary>
        public static string ContainerIsTheNameOfTheContainer {
            get {
                return ResourceManager.GetString("ContainerIsTheNameOfTheContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data Formats.
        /// </summary>
        public static string DataFormats {
            get {
                return ResourceManager.GetString("DataFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;i&gt;dataset&lt;/i&gt; is the name of the data set (for example, &quot;CrimeIncidents&quot; for the
        ///				Crime Incidents data set in the DC container)..
        /// </summary>
        public static string DatasetIsTheNameOfTheDataSet {
            get {
                return ResourceManager.GetString("DatasetIsTheNameOfTheDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Developers using &lt;a href=&quot;http://www.microsoft.com/vstudio&quot;
        ///				target=&quot;_blank&quot;&gt;Microsoft Visual Studio 2010&lt;/a&gt;&lt;img
        ///				 src=&quot;/Images/ExternalLink.png&quot;
        ///					alt=&quot;Click to get Microsoft Visual Studio 2010&quot; 
        ///					title=&quot;Microsoft Visual Studio 2010&quot; 
        ///					longdesc=&quot;/Descriptions/VS2010.txt&quot; /&gt;
        ///			(or later) can use &lt;a href=&quot;http://msdn.microsoft.com/en-us/data/bb931106.aspx&quot;
        ///				target=&quot;_blank&quot;&gt;WCF Data Services&lt;/a&gt;&lt;img
        ///				 src=&quot;/Images/ExternalLink.png&quot;
        ///					alt=&quot;Click to get WCF Data Services&quot; 
        ///					title [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string DevelopersUsingVisualStudio2010 {
            get {
                return ResourceManager.GetString("DevelopersUsingVisualStudio2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For Developers.
        /// </summary>
        public static string ForDevelopers {
            get {
                return ResourceManager.GetString("ForDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geospatial Data.
        /// </summary>
        public static string GeospatialData {
            get {
                return ResourceManager.GetString("GeospatialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON.
        /// </summary>
        public static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSONP.
        /// </summary>
        public static string JSONP {
            get {
                return ResourceManager.GetString("JSONP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Many of the data sets in OGDI DataLab also include geospatial data, which is returned in
        ///			the &lt;a href=&quot;http://en.wikipedia.org/wiki/Keyhole_Markup_Language&quot; target=&quot;_blank&quot;&gt;
        ///				Keyhole Markup Language (KML)&lt;/a&gt;&lt;img src=&quot;/Images/ExternalLink.png&quot;
        ///					alt=&quot;Click to get Keyhole Markup Language&quot; 
        ///					title=&quot;Keyhole Markup Language (KML)&quot;
        ///					longdesc=&quot;/Descriptions/KML.txt&quot; /&gt;
        ///			format. This format is compatible with popular desktop and Web-based mapping technologies
        ///			including Microsoft &lt;a href=&quot;http: [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string ManyOfTheDataSetsInOGDI {
            get {
                return ResourceManager.GetString("ManyOfTheDataSetsInOGDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note that if the data set that you are using does not include any geospatial data,
        ///			a KML query to OGDI DataLab will return an empty result set..
        /// </summary>
        public static string NoteThatIfTheDataSet {
            get {
                return ResourceManager.GetString("NoteThatIfTheDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note that OGDI DataLab currently only supports  the $filter and $top query options in the
        ///			WCF Data Services query syntax..
        /// </summary>
        public static string NoteThatOGDICurrentlyOnlySupportsThe {
            get {
                return ResourceManager.GetString("NoteThatOGDICurrentlyOnlySupportsThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OGDI DataLab and the underlying Windows Azure Table Storage service support paging through
        ///			large sets of query results. The documentation for &lt;a
        ///			 href=&quot;http://msdn.microsoft.com/en-us/library/dd135718.aspx&quot;
        ///				target=&quot;_blank&quot;&gt;Query Timeout and Pagination&lt;/a&gt;&lt;img
        ///				 src=&quot;/Images/ExternalLink.png&quot;
        ///					alt=&quot;Click to get Query Timeout and Pagination&quot; 
        ///					title=&quot;Query Timeout and Pagination&quot; 
        ///					longdesc=&quot;/Descriptions/QueryTimeoutPagination.txt&quot; /&gt;
        ///			in the Windows Azure Table Storage service pro [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string OGDIAndTheUnderlyingWindowsAzureTableStorageService {
            get {
                return ResourceManager.GetString("OGDIAndTheUnderlyingWindowsAzureTableStorageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OGDI Lab can also return data in the &lt;a href=&quot;http://en.wikipedia.org/wiki/JSON&quot;
        ///				target=&quot;_blank&quot;&gt;JavaScript Object Notation (JSON)&lt;/a&gt;&lt;img
        ///				src=&quot;/Images/ExternalLink.png&quot;
        ///					alt=&quot;Click to get JavaScript Object Notation&quot; 
        ///					title=&quot;JavaScript Object Notation (JSON)&quot; 
        ///					longdesc=&quot;/Descriptions/Json.txt&quot; /&gt;
        ///			format, which can be conveniently consumed using JavaScript and other technologies.
        ///			To return data in JSON format, simply append the format=json parameter to your query.
        ///			For example,  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string OGDICanAlsoReturnDataInTheJSON {
            get {
                return ResourceManager.GetString("OGDICanAlsoReturnDataInTheJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OGDI DataLab can also return data in the &lt;a href=&quot;http://en.wikipedia.org/wiki/Resource_Description_Framework&quot;
        ///    target=&quot;_blank&quot;&gt;RDF (Resource Description Framework)&lt;/a&gt;&lt;img src=&quot;/Images/ExternalLink.png&quot;
        ///                longdesc=&quot;/Descriptions/Json.txt&quot; /&gt; format. RDF is a graph model for describing formally web resources and their associated metadata. Developed by W3C, RDF is a base language for semantic Web. To return data in RDF format, simply append the format=rdf parameter to your query:.
        /// </summary>
        public static string OGDICanAlsoReturnDataInTheRDF {
            get {
                return ResourceManager.GetString("OGDICanAlsoReturnDataInTheRDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OGDI DataLab&apos;s data services also provide direct support for the &lt;a
        ///			 href=&quot;http://en.wikipedia.org/wiki/JSON#JSONP&quot;
        ///					target=&quot;_blank&quot;&gt;JSONP&lt;/a&gt;&lt;img 
        ///					src=&quot;/Images/ExternalLink.png&quot;
        ///					alt=&quot;Click to get JSONP&quot; 
        ///					title=&quot;JSONP&quot;
        ///					longdesc=&quot;/Descriptions/JSONP.txt&quot; /&gt;
        ///			technique. Using this technique, OGDI&apos;s data services will call a callback function
        ///			that you specify, passing in the results of your query in JSON format as an input
        ///			format. To use this technique, issue a query with the [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string OGDIDataServicesAlsoProvideDirectSupportForTheJSONP {
            get {
                return ResourceManager.GetString("OGDIDataServicesAlsoProvideDirectSupportForTheJSONP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;blockquote&gt;
        ///                http://ogdi.cloudapp.net/v1/dc/CrimeIncidents?$filter=shift eq &apos;EVN&apos;&amp;format={0}&lt;/blockquote&gt;.
        /// </summary>
        public static string OGDIDemoURLFormat {
            get {
                return ResourceManager.GetString("OGDIDemoURLFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OGDI DataLab exposes data through &lt;a href=&quot;http://en.wikipedia.org/wiki/Representational_State_Transfer&quot; target=&quot;_blank&quot;&gt;
        ///				REST&lt;/a&gt;&lt;img src=&quot;/Images/ExternalLink.png&quot;
        ///					alt=&quot;Click to get REST article on the Wikipedia&quot; 
        ///					title=&quot;REST&quot;
        ///					longdesc=&quot;/Descriptions/REST.txt&quot; /&gt; Web services. 
        ///					The basic format of an OGDI service call is 
        ///					http://ogdi.cloudapp.net/v1/&lt;i&gt;container&lt;/i&gt;/&lt;i&gt;dataset&lt;/i&gt;?&lt;i&gt;query&lt;/i&gt;,
        ///			where:.
        /// </summary>
        public static string OGDIExposesDataThrough {
            get {
                return ResourceManager.GetString("OGDIExposesDataThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paging.
        /// </summary>
        public static string Paging {
            get {
                return ResourceManager.GetString("Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;project&gt; is the name of the service project for the publication service based on the OGDI DataLab starter kit in Windows Azure (&quot;ogdifrancedataservice&quot; for example).
        /// </summary>
        public static string ProjectEstLeNomDuProjet {
            get {
                return ResourceManager.GetString("ProjectEstLeNomDuProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Querying OGDI DataLab.
        /// </summary>
        public static string QueryingOGDI {
            get {
                return ResourceManager.GetString("QueryingOGDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;i&gt;query&lt;/i&gt; is your set of query parameters, expressed using a subset of the &lt;a
        ///				href=&quot;http://msdn.microsoft.com/en-us/library/cc668784(VS.100).aspx&quot; target=&quot;_blank&quot;&gt;WCF
        ///				Data Services query syntax.&lt;/a&gt;&lt;img src=&quot;/Images/ExternalLink.png&quot;
        ///					alt=&quot;Click to get WCF Data Services query syntax&quot; 
        ///					title=&quot;WCF Data Services query syntax&quot; 
        ///					longdesc=&quot;/Descriptions/ADOquerysyntax.txt&quot; /&gt;.
        /// </summary>
        public static string QueryIsYourSetOfQueryParameters {
            get {
                return ResourceManager.GetString("QueryIsYourSetOfQueryParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RDF.
        /// </summary>
        public static string RDF {
            get {
                return ResourceManager.GetString("RDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refer to the JavaScript sample on the &lt;a href=&quot;/DataBrowser/dc/CrimeIncidents#param=NOFILTER--DataView--Results&quot;&gt;
        ///				Data Browser&lt;/a&gt; page for an example of using JSONP with OGDI DataLab. In that sample,
        ///			the AdditionalDataLoaded() function is the JSONP callback function..
        /// </summary>
        public static string ReferToTheJavaScriptSampleOnThe {
            get {
                return ResourceManager.GetString("ReferToTheJavaScriptSampleOnThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OGDI DataLab is written using C# and the .NET Framework, targeted for Microsoft&apos;s
        ///                &lt;a href=&quot;http://www.windowsazure.com/&quot;&gt;Windows Azure Platform&lt;/a&gt; cloud-computing
        ///                platform. Data Service.&lt;br /&gt;&lt;br /&gt;                The DataService uses RESTful Web service to expose data for programmatic access
        ///                via a number of formats, including Open Data Protocol (OData)**, an extension to
        ///                **Atom Publishing Protocol (AtomPub), Keyhole Markup Language (KML), JSO [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string TheOpenGovernmentDataInitiativeIsBased {
            get {
                return ResourceManager.GetString("TheOpenGovernmentDataInitiativeIsBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overview.
        /// </summary>
        public static string TheWindowsAzurePlatform {
            get {
                return ResourceManager.GetString("TheWindowsAzurePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To mitigate security vulnerabilities associated with cross-site scripting attacks,
        ///			Web browsers generally prevent client-side JavaScript applications originating in
        ///			one network domain (for example, yourdomain.com) from making HTTP requests to other
        ///			network domains (for example, the ogdi.cloudapp.net network domain that hosts the
        ///			OGDI DataLab data services). This can prevent JavaScript applications hosted in another
        ///			domain from making straight-forward calls to the OGDI DataLab data services, b [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string ToMitigateSecurityVulnerabilities {
            get {
                return ResourceManager.GetString("ToMitigateSecurityVulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To return geospatial data in KML format, append the format=kml parameter to your
        ///			query. For example, to retrieve geospatial points in KML format for crime incidents
        ///			in DC that occurred during the police department&apos;s evening shift:.
        /// </summary>
        public static string ToReturnGeospatialDataInKMLFormat {
            get {
                return ResourceManager.GetString("ToReturnGeospatialDataInKMLFormat", resourceCulture);
            }
        }
    }
}
