//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBrowserResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataSetData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataSetData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogdi.InteractiveSdk.Mvc.Resources.Views.DataBrowser.DataSetData", typeof(DataSetData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (additional $filter parameters...).
        /// </summary>
        public static string AdditionalFilterParameters {
            get {
                return ResourceManager.GetString("AdditionalFilterParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate.
        /// </summary>
        public static string Aggregate {
            get {
                return ResourceManager.GetString("Aggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Chart.
        /// </summary>
        public static string BarChart {
            get {
                return ResourceManager.GetString("BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click to view results as JSON).
        /// </summary>
        public static string ClickToViewResultsAsXMLKML {
            get {
                return ResourceManager.GetString("ClickToViewResultsAsXMLKML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data View.
        /// </summary>
        public static string DataView {
            get {
                return ResourceManager.GetString("DataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entityset&lt;br /&gt;Column:&amp;nbsp;&amp;nbsp;.
        /// </summary>
        public static string EntitysetColumn {
            get {
                return ResourceManager.GetString("EntitysetColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full query URL:.
        /// </summary>
        public static string FullQueryURL {
            get {
                return ResourceManager.GetString("FullQueryURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Axis.
        /// </summary>
        public static string HorizontalAxis {
            get {
                return ResourceManager.GetString("HorizontalAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map View.
        /// </summary>
        public static string MapView {
            get {
                return ResourceManager.GetString("MapView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of occurrences of.
        /// </summary>
        public static string NoOfOccurrencesOf {
            get {
                return ResourceManager.GetString("NoOfOccurrencesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of placemarks in a result set exceeds the pin display count limit (50 placemarks).
        /// </summary>
        public static string NumberOfPlacemarksInAResultSetExceedsThePinDisplayCountLimit {
            get {
                return ResourceManager.GetString("NumberOfPlacemarksInAResultSetExceedsThePinDisplayCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 1.
        /// </summary>
        public static string Option1 {
            get {
                return ResourceManager.GetString("Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 2.
        /// </summary>
        public static string Option2 {
            get {
                return ResourceManager.GetString("Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie Chart.
        /// </summary>
        public static string PieChart {
            get {
                return ResourceManager.GetString("PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid column from list..
        /// </summary>
        public static string PleaseSelectValidColumnFromList {
            get {
                return ResourceManager.GetString("PleaseSelectValidColumnFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query_Syntax.
        /// </summary>
        public static string QuerySyntax {
            get {
                return ResourceManager.GetString("QuerySyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OGDI DataLab&apos;s data service enables to specify a set of query parameters, expressed using a subset of the &lt;a href=&quot;http://www.odata.org/documentation/&quot; target=&quot;_blank&quot;&gt;OData query syntax&lt;/a&gt;. OGDI DataLab currently only supports the $top, $skip, $orderby, $filter and $top query options in the OData query syntax. &lt;/p&gt;&lt;p&gt;
        ///Also note that if a property has a null value for a particular entity in the data set, it will be omitted entirely from the result set returned by OGDI DataLab. Your (modern) applicatio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QuerySyntaxText {
            get {
                return ResourceManager.GetString("QuerySyntaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range:.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh-chart.
        /// </summary>
        public static string RefreshChart {
            get {
                return ResourceManager.GetString("RefreshChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected data does not have location information..
        /// </summary>
        public static string SelectedDataDoesNotHaveLocationInformation {
            get {
                return ResourceManager.GetString("SelectedDataDoesNotHaveLocationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select one).
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Axis.
        /// </summary>
        public static string VerticalAxis {
            get {
                return ResourceManager.GetString("VerticalAxis", resourceCulture);
            }
        }
    }
}
