//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBrowserResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataSetData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataSetData() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogdi.InteractiveSdk.Mvc.Resources.Views.DataBrowser.DataSetData", typeof(DataSetData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (additional $filter parameters...).
        /// </summary>
        public static string AdditionalFilterParameters {
            get {
                return ResourceManager.GetString("AdditionalFilterParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aggregate.
        /// </summary>
        public static string Aggregate {
            get {
                return ResourceManager.GetString("Aggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bar Chart.
        /// </summary>
        public static string BarChart {
            get {
                return ResourceManager.GetString("BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Click to view results as XML/KML).
        /// </summary>
        public static string ClickToViewResultsAsXMLKML {
            get {
                return ResourceManager.GetString("ClickToViewResultsAsXMLKML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crime incidents where the method code is equal to 2. Other comparison operators
        ///                        include &amp;quot;gt&amp;quot; for greater than, &amp;quot;lt&amp;quot; for less than, &amp;quot;ge&amp;quot;
        ///                        for greater than or equal to, and &amp;quot;le&amp;quot; for less than or equal to..
        /// </summary>
        public static string CrimeIncidentsWhereTheMethodCode {
            get {
                return ResourceManager.GetString("CrimeIncidentsWhereTheMethodCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crime incidents where the report date/time is on or after midnight, June 1, 2008,
        ///                        UTC. Date/time literals are expressed in &lt;a 
        ///                        href=&quot;http://en.wikipedia.org/wiki/ISO_8601&quot; target=&quot;_blank&quot;&gt;ISO 8601&lt;/a&gt;&lt;img 
        ///                        src=&quot;/Images/ExternalLink.png&quot;
        ///                        alt=&quot;DBPC_ISO8601AltText&quot; 
        ///                        title=&quot;ISO 8601&quot;
        ///                        longdesc=&quot;/Descriptions/Iso.txt&quot; /&gt;
        ///                        format, &lt;i&gt;yyyy&lt;/i&gt;-&lt;i&gt;mm&lt;/ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string CrimeIncidentsWhereTheReportDatetime {
            get {
                return ResourceManager.GetString("CrimeIncidentsWhereTheReportDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crime incidents where the shift is equal to &amp;quot;EVN;&amp;quot; or &amp;quot;MID&amp;quot;.
        ///                        The filter syntax supports the &amp;quot;and&amp;quot;, &amp;quot;or&amp;quot;, and &amp;quot;not&amp;quot;
        ///                        logical operators. Expressions can grouped with parentheses, as in many popular
        ///                        programming languages..
        /// </summary>
        public static string CrimeIncidentsWhereTheShiftIsEqualTo {
            get {
                return ResourceManager.GetString("CrimeIncidentsWhereTheShiftIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crime incidents where the &amp;quot;shift&amp;quot; property is equal to &amp;quot;EVN&amp;quot;.
        ///                        String literals must be enclosed in single quotes. Boolean literals are represented
        ///                        as &amp;quot;true&amp;quot; or &amp;quot;false&amp;quot; (without the double quotes)..
        /// </summary>
        public static string CrimeIncidentsWhereTheShiftProperty {
            get {
                return ResourceManager.GetString("CrimeIncidentsWhereTheShiftProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data View.
        /// </summary>
        public static string DataView {
            get {
                return ResourceManager.GetString("DataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entityset&lt;br /&gt;Column:&amp;nbsp;&amp;nbsp;.
        /// </summary>
        public static string EntitysetColumn {
            get {
                return ResourceManager.GetString("EntitysetColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full query URL:.
        /// </summary>
        public static string FullQueryURL {
            get {
                return ResourceManager.GetString("FullQueryURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horizontal Axis.
        /// </summary>
        public static string HorizontalAxis {
            get {
                return ResourceManager.GetString("HorizontalAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map View.
        /// </summary>
        public static string MapView {
            get {
                return ResourceManager.GetString("MapView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No. of occurrences of.
        /// </summary>
        public static string NoOfOccurrencesOf {
            get {
                return ResourceManager.GetString("NoOfOccurrencesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of placemarks in a result set exceeds the pin display count limit (50 placemarks).
        /// </summary>
        public static string NumberOfPlacemarksInAResultSetExceedsThePinDisplayCountLimit {
            get {
                return ResourceManager.GetString("NumberOfPlacemarksInAResultSetExceedsThePinDisplayCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OGDI uses a subset of the &lt;a 
        ///            href=&quot;http://msdn.microsoft.com/en-us/library/cc668784(VS.100).aspx&quot;&gt;
        ///                WCF Data Services query syntax&lt;/a&gt;&lt;img
        ///                src=&apos;/Images/ExternalLink.png&apos;
        ///                alt=&apos;Click to get WCF Data Services query syntax&apos;
        ///                title=&apos;WCF Data Services query syntax&apos;
        ///                longdesc=&apos;/Descriptions/ADOquerysyntax.txt&apos; /&gt;. The basic format
        ///            of a filter expression is &lt;i&gt;property&lt;/i&gt;&amp;nbsp;&lt;i&gt;comparison&lt;/i&gt;&amp;nbsp;&lt;i&gt;expression&lt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string OGDIUsesASubsetOf {
            get {
                return ResourceManager.GetString("OGDIUsesASubsetOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option 1.
        /// </summary>
        public static string Option1 {
            get {
                return ResourceManager.GetString("Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option 2.
        /// </summary>
        public static string Option2 {
            get {
                return ResourceManager.GetString("Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pie Chart.
        /// </summary>
        public static string PieChart {
            get {
                return ResourceManager.GetString("PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select valid column from list..
        /// </summary>
        public static string PleaseSelectValidColumnFromList {
            get {
                return ResourceManager.GetString("PleaseSelectValidColumnFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Range:.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à refresh-chart.
        /// </summary>
        public static string RefreshChart {
            get {
                return ResourceManager.GetString("RefreshChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected data does not have location information..
        /// </summary>
        public static string SelectedDataDoesNotHaveLocationInformation {
            get {
                return ResourceManager.GetString("SelectedDataDoesNotHaveLocationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Select one).
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some examples of filter expressions using the CrimeIncidents data set from the DC  container are:.
        /// </summary>
        public static string SomeExamplesOfFilterExpressions {
            get {
                return ResourceManager.GetString("SomeExamplesOfFilterExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vertical Axis.
        /// </summary>
        public static string VerticalAxis {
            get {
                return ResourceManager.GetString("VerticalAxis", resourceCulture);
            }
        }
    }
}
