//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBrowserResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataSetDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataSetDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogdi.InteractiveSdk.Mvc.Resources.Views.DataBrowser.DataSetDetails", typeof(DataSetDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string Additionalnformation {
            get {
                return ResourceManager.GetString("Additionalnformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Instruments.
        /// </summary>
        public static string CollectionInstruments {
            get {
                return ResourceManager.GetString("CollectionInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Mode.
        /// </summary>
        public static string CollectionMode {
            get {
                return ResourceManager.GetString("CollectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Dictionary/Variables.
        /// </summary>
        public static string DataDictionaryVariables {
            get {
                return ResourceManager.GetString("DataDictionaryVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset Details.
        /// </summary>
        public static string DatasetDetails {
            get {
                return ResourceManager.GetString("DatasetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset name.
        /// </summary>
        public static string DatasetName {
            get {
                return ResourceManager.GetString("DatasetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source.
        /// </summary>
        public static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date.
        /// </summary>
        public static string ExpiredDate {
            get {
                return ResourceManager.GetString("ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic area covered.
        /// </summary>
        public static string GeographicAreaCovered {
            get {
                return ResourceManager.GetString("GeographicAreaCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated Date.
        /// </summary>
        public static string LastUpdatedDate {
            get {
                return ResourceManager.GetString("LastUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links and references.
        /// </summary>
        public static string LinksAndReferences {
            get {
                return ResourceManager.GetString("LinksAndReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Url.
        /// </summary>
        public static string MetadataUrl {
            get {
                return ResourceManager.GetString("MetadataUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released Date.
        /// </summary>
        public static string ReleasedDate {
            get {
                return ResourceManager.GetString("ReleasedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Documentation.
        /// </summary>
        public static string TechnicalDocumentation {
            get {
                return ResourceManager.GetString("TechnicalDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time period covered.
        /// </summary>
        public static string TimePeriodCovered {
            get {
                return ResourceManager.GetString("TimePeriodCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update frequency.
        /// </summary>
        public static string UpdateFrequency {
            get {
                return ResourceManager.GetString("UpdateFrequency", resourceCulture);
            }
        }
    }
}
