//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OGDIMasterPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OGDIMasterPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogdi.InteractiveSdk.Mvc.Resources.Views.Shared.OGDIMasterPage", typeof(OGDIMasterPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about Microsoft.
        /// </summary>
        public static string AboutWebSite {
            get {
                return ResourceManager.GetString("AboutWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com/about/en/us/default.aspx.
        /// </summary>
        public static string AboutWebSiteURL {
            get {
                return ResourceManager.GetString("AboutWebSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact Microsoft.
        /// </summary>
        public static string ContactMicrosoft {
            get {
                return ResourceManager.GetString("ContactMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://support.microsoft.com/contactus/?ln=en.
        /// </summary>
        public static string ContactMicrosoftURL {
            get {
                return ResourceManager.GetString("ContactMicrosoftURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers.
        /// </summary>
        public static string Developers {
            get {
                return ResourceManager.GetString("Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opendata_en.png.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage your profile.
        /// </summary>
        public static string ManageYourProfile {
            get {
                return ResourceManager.GetString("ManageYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://profile.microsoft.com/RegSysProfileCenter/default.aspx?lcid=1033.
        /// </summary>
        public static string ManageYourProfileURL {
            get {
                return ResourceManager.GetString("ManageYourProfileURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2010 Microsoft Corporation. All rights reserved..
        /// </summary>
        public static string MicrosoftCorporationAllRightsReserved {
            get {
                return ResourceManager.GetString("MicrosoftCorporationAllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy statement.
        /// </summary>
        public static string PrivacyStatement {
            get {
                return ResourceManager.GetString("PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://privacy.microsoft.com/en-us/default.mspx.
        /// </summary>
        public static string PrivacyStatementURL {
            get {
                return ResourceManager.GetString("PrivacyStatementURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms of use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.microsoft.com/?linkid=4412892.
        /// </summary>
        public static string TermsOfUseURL {
            get {
                return ResourceManager.GetString("TermsOfUseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trademarks.
        /// </summary>
        public static string Trademarks {
            get {
                return ResourceManager.GetString("Trademarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com/library/toolbar/3.0/trademarks/en-us.mspx.
        /// </summary>
        public static string TrademarksURL {
            get {
                return ResourceManager.GetString("TrademarksURL", resourceCulture);
            }
        }
    }
}
